services:
    condor:
        image: condor:latest
        network_mode: "host"        
        volumes:
            - /firmware:/firmware
        entrypoint: /firmware/entrypoint.sh
        restart: on-failure
