[package]
name = "hmi_bridge"
version = "0.1.0"
edition = "2024"

[profile.colcon]
inherits = "release"

[dependencies]
r2r = "0.9.5"
futures = "0.3.31"
anyhow = "1.0.100"
serde = "1.0.228"
serde_json = "1.0.146"
autoplane_hmi_lib = {path = "../../../autoplane-hmi/autoplane_hmi_lib"}
